version: "3.8"

services:
  db:
    image: postgres:13.17-alpine
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "./tmp/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  
  api:
    build:
      context: .
      args:
        WORKDIR: /app
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ".:/app"
    depends_on:
      - db
    ports:
      - "3000:3000"


